apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: game-jam-abstraction
  label: game-jam-abstraction
spec:
  hosts:
  - "*"
  gateways:
  - chainabstractiongateway
  http:
  - match:
    - uri:
        exact: /api/v1/health/status
    - uri:
        exact: /api/v1/manager/get-all-gamejams
    - uri:
        prefix: /api/v1/swagger/docs/
    route:
    - destination:
        host: game-jam-abstraction
        port:
          number: 80